### ISSUE TITLE
虚拟机踩坑记录

### ISSUE THREAD

**Issue by harahi** [harahi/blog#3]
## 起因

起初使用WSL作为本地开发虚拟机。

但由于各种原因，需要虚拟机多网卡（Host-only, Bridged），并且需要部署两台虚拟机。此时查阅WSL，相关资料极少，并且目前WSL管理很不完善，最后痛定思痛还是转回VMware Workstation。

之所以没选择VirtualBox是因为历史原因，之前工作中有些老虚拟机是VM。

估计下台laptop系统会选择Linux发行版，可能是Ubuntu，也可能是Arch（谁不是个Archer呢），KVM真香。

## VMware Workstation Network Configuration

1. `Edit`
2. `Virtual Network Editor`
3. `Change Settings`
4. VMnet0: select target network which can access the Internet in `Bridged to`
5. `Add Network...`
6. Details: 
   1. VMnet1: set as Host-only
   2. VMnet8: set as NAT
   3. Check `Connet a host...` and `Use local DHCP...`
   4. Manually set `Subnet IP`
   5. Manually set `Starting IP address` and `Ending IP address` in `DHCP Setting`

![Snipaste_2023-08-07_20-27-55](https://github.com/harahi/blog/assets/23181761/d5f125a9-4b41-4768-84bf-522c24dd9a46)

## Ubuntu Netplan

When I set two Network Adapter, my config is below:

```yaml
network:
  version: 2
  ethernets:
    ens33:
      link-local: [ ipv4 ]
      dhcp4: true
      optional: true
    ens37:
      link-local: [ ipv4 ]
      dhcp4: false
      optional: true
      addresses: [192.168.1.21/24]
      nameservers:
        search: []
        addresses: [223.6.6.6, 1.0.0.1]
      routes:
        - to: default
          via: 192.168.1.1
```
